
[Gameplay]
	#On world creation, the player is given an Aether Portal Frame item to automatically go to the Aether with
	"Gives player Aether Portal Frame item" = false
	#When the player enters the Aether, they are given a Book of Lore and Golden Parachutes as starting loot
	"Gives starting loot on entry" = true
	#Determines whether the Sun Spirit's dialogue when meeting him should play through every time you meet him
	"Repeat Sun Spirit's battle dialogue" = true

